[build-system] 
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name =  # name of the installed package
version = 0.0.1 # version is required
dependencies = [ # specify the required package dependencies
    "rdkit",
]